<?php

declare(strict_types=1);

namespace cronvTaskManagementMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240407032711 extends AbstractMigration
{
    /**
     * Migration Description
     *
     * @return string
     */
    public function getDescription(): string
    {
        return 'Create tables for transactions';
    }

    /**
     * Applying Migration
     *
     * @param Schema $schema An object representation of a database schema.
     *
     * @return void
     */
    public function up(Schema $schema): void
    {
        //--------------------------------------------------------------------------------
        // Таблица типов финансовых операций
        $this->addSql('
        CREATE TABLE transaction_type (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(64) NOT NULL
        );');
        $this->addSql("COMMENT ON TABLE transaction_type IS 'Список расходов';");
        $this->addSql("COMMENT ON COLUMN transaction_type.id IS 'Идентификатор';");
        $this->addSql("COMMENT ON COLUMN transaction_type.name IS 'Название';");

        //--------------------------------------------------------------------------------
        // Таблица финансовых операций
        $this->addSql('
        CREATE TABLE transaction (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            type_id INTEGER NOT NULL,
            user_id INT NOT NULL,
            amount DECIMAL(10,2) NOT NULL,
            description TEXT,
            dated_at DATE NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
        );');

        $this->addSql('CREATE INDEX idx_transaction__user_id ON transaction(user_id);');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT "fk_transaction__type_id-transaction_type" FOREIGN KEY (type_id) REFERENCES transaction_type(id);');

        $this->addSql("COMMENT ON TABLE transaction IS 'Список расходов';");
        $this->addSql("COMMENT ON COLUMN transaction.type_id IS 'Внешний ключ transaction_type.id';");
        $this->addSql("COMMENT ON COLUMN transaction.user_id IS 'Внешний ключ users.id';");
        $this->addSql("COMMENT ON COLUMN transaction.amount IS 'Сумма';");
        $this->addSql("COMMENT ON COLUMN transaction.description IS 'Описание';");
        $this->addSql("COMMENT ON COLUMN transaction.dated_at IS 'Дата';");
        $this->addSql("COMMENT ON COLUMN transaction.created_at IS 'Дата и время создания';");
    }

    /**
     * Rolling back a migration
     *
     * @param Schema $schema An object representation of a database schema.
     * @return void
     */
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS transaction, transaction_type;');
    }
}
